nodeLinker: node-modules
npmRegistryServer: "https://registry.yarnpkg.com"

supportedArchitectures:
    os:
        - current
        - linux
    cpu:
        - current
        - arm64
    libc:
        - glibc
        - musl
